language: python
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
#  - python checkfiles.py
  - curl https://nhentai.net/search?q=%E4%BA%8C%E5%B3%B0%E8%B7%A8%E4%BA%BA