language: python
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
#  - python checkfiles.py
  - curl https://www.javlibrary.com/tw/star_list.php?prefix=A